[a64] Fix MSVC-ARM64 `MemoryBarrier` preprocessor conflict
Fixes a build error on MSVC when building for ARM. Though there might be a better way to fix this.
```
hir_builder.h(206,8): error C2061: syntax error: identifier '_ARM64_BARRIER_SY'
```
`MemoryBarrier` resolves into a preprocessor when building on MSVC-ARM64 in particular.